export interface MockDebtItem {
  id: string;
  title: string;
  counterpartName: string;
  type: 'I_OWE' | 'THEY_OWE_ME';
  totalAmount: number;
  paidAmount: number;
  currency: string;
  dueDate?: string;
  notes?: string;
  isSettled: boolean;
}

export interface MockCoupleExpense {
  id: string;
  title: string;
  totalAmount: number;
  currency: string;
  category: string;
  paidBy: 'USER' | 'PARTNER';
  userShareRatio: number;
  partnerShareRatio: number;
  date: string;
  isSettled: boolean;
}

export const INITIAL_SUMMARY = {
  netWorthInBaseCurrency: 24170.5,
  totalIncomeThisMonth: 9500.0,
  totalExpensesThisMonth: 3825.4,
  netSavingsThisMonth: 5674.6,
  savingsRatePercentage: 59.7,
  rule503020: {
    needsAmount: 2150.0,
    needsPercentage: 56.2,
    wantsAmount: 975.4,
    wantsPercentage: 25.5,
    savingsAmount: 700.0,
    savingsPercentage: 18.3,
  },
  cashFlowRunwayDays: 185,
  currency: 'BOB',
  customPaydayDay: 25,
  daysUntilNextPayday: 6,
  dailySafeSpendBudget: 175.5,
};

export const INITIAL_ACCOUNTS = [
  {
    id: 'acc-1',
    name: 'BCP Sueldo & QR',
    type: 'CHECKING',
    currency: 'BOB',
    balance: 7850.5,
    institutionName: 'Banco de Crédito BCP',
    accountNumberMask: '****4431',
    color: '#2563eb',
    icon: 'landmark',
  },
  {
    id: 'acc-2',
    name: 'Caja de Ahorros BNB',
    type: 'SAVINGS',
    currency: 'BOB',
    balance: 5400.0,
    institutionName: 'Banco Nacional de Bolivia',
    accountNumberMask: '****8912',
    color: '#059669',
    icon: 'wallet',
  },
  {
    id: 'acc-3',
    name: 'Ahorros Dólares USD',
    type: 'SAVINGS',
    currency: 'USD',
    balance: 1500.0,
    institutionName: 'Banco Bisa',
    accountNumberMask: '****2290',
    color: '#0d9488',
    icon: 'dollar-sign',
  },
  {
    id: 'acc-4',
    name: 'Billetera Efectivo',
    type: 'CASH',
    currency: 'BOB',
    balance: 420.0,
    color: '#ca8a04',
    icon: 'banknote',
  },
  {
    id: 'acc-5',
    name: 'Binance USDT Crypto',
    type: 'CRYPTO',
    currency: 'USDT',
    balance: 500.0,
    color: '#f59e0b',
    icon: 'coins',
  },
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 'tx-1',
    merchantName: 'Hipermaxi El Prado',
    accountName: 'BCP Sueldo & QR',
    categoryName: 'Supermercado & Víveres',
    categoryColor: '#16a34a',
    classification: 'NEEDS',
    amount: 245.5,
    currency: 'BOB',
    type: 'EXPENSE',
    source: 'SMS_PARSER',
    date: '2026-08-28T14:30:00Z',
    notes: 'Parseado automático desde SMS BCP',
  },
  {
    id: 'tx-2',
    merchantName: 'Café Typica Cochabamba',
    accountName: 'BCP Sueldo & QR',
    categoryName: 'Restaurantes & Cafés',
    categoryColor: '#ec4899',
    classification: 'WANTS',
    amount: 110.0,
    currency: 'BOB',
    type: 'EXPENSE',
    source: 'PUSH_NOTIFICATION',
    date: '2026-08-27T18:15:00Z',
    notes: 'Almuerzo y café especial',
  },
  {
    id: 'tx-3',
    merchantName: 'Nómina Empresa Tech SRL',
    accountName: 'BCP Sueldo & QR',
    categoryName: 'Sueldo & Honorarios',
    categoryColor: '#10b981',
    classification: 'INCOME',
    amount: 9500.0,
    currency: 'BOB',
    type: 'INCOME',
    source: 'BANK_SYNC',
    date: '2026-08-25T09:00:00Z',
    notes: 'Abono de salario mensual',
  },
  {
    id: 'tx-4',
    merchantName: 'Netflix Premium',
    accountName: 'Caja de Ahorros BNB',
    categoryName: 'Suscripciones Digitales',
    categoryColor: '#06b6d4',
    classification: 'WANTS',
    amount: 69.9,
    currency: 'BOB',
    type: 'EXPENSE',
    source: 'MANUAL',
    date: '2026-08-22T10:00:00Z',
    notes: 'Suscripción streaming',
  },
  {
    id: 'tx-5',
    merchantName: 'Farmacorp Cala Cala',
    accountName: 'BCP Sueldo & QR',
    categoryName: 'Salud & Medicamentos',
    categoryColor: '#ef4444',
    classification: 'NEEDS',
    amount: 185.0,
    currency: 'BOB',
    type: 'EXPENSE',
    source: 'SMS_PARSER',
    date: '2026-08-20T19:40:00Z',
    notes: 'Medicamentos y botiquín',
  },
];

export const CASHFLOW_HISTORY = [
  { month: 'Mar', income: 8200, expenses: 4100 },
  { month: 'Abr', income: 8200, expenses: 3900 },
  { month: 'May', income: 8500, expenses: 4300 },
  { month: 'Jun', income: 9000, expenses: 4600 },
  { month: 'Jul', income: 9000, expenses: 4150 },
  { month: 'Ago', income: 9500, expenses: 3825 },
];

export const INITIAL_FIXED_EXPENSES = [
  // Inversiones Recurrentes (Págate a ti primero)
  {
    id: 'fx-inv-1',
    name: 'Aporte Mensual DPF / Depósito a Plazo',
    categoryName: 'Inversión & Retiro',
    type: 'INVESTMENT_DCA',
    amount: 1000.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 25,
    autoDeduct: true,
    color: '#10b981',
    icon: 'trending-up',
    isPaidThisMonth: true,
  },
  {
    id: 'fx-inv-2',
    name: 'Compra Recurrente DCA Cripto (USDT/BTC)',
    categoryName: 'Inversión & Cripto',
    type: 'INVESTMENT_DCA',
    amount: 500.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 26,
    autoDeduct: false,
    color: '#f59e0b',
    icon: 'coins',
    isPaidThisMonth: true,
  },
  {
    id: 'fx-inv-3',
    name: 'Fondo de Inversión Abierto SAFI',
    categoryName: 'Inversión & Retiro',
    type: 'INVESTMENT_DCA',
    amount: 700.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 28,
    autoDeduct: true,
    color: '#059669',
    icon: 'landmark',
    isPaidThisMonth: false,
  },

  // Vivienda / Alquiler / Hipoteca
  {
    id: 'fx-1',
    name: 'Alquiler Depto Cala Cala',
    categoryName: 'Vivienda',
    type: 'HOUSING',
    amount: 1800.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 5,
    autoDeduct: false,
    color: '#2563eb',
    icon: 'home',
    isPaidThisMonth: true,
  },

  // Servicios Básicos
  {
    id: 'fx-2',
    name: 'Luz (ELFEC Cochabamba)',
    categoryName: 'Servicios Básicos',
    type: 'FIXED_UTILITY',
    amount: 140.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 12,
    autoDeduct: true,
    color: '#eab308',
    icon: 'zap',
    isPaidThisMonth: true,
  },
  {
    id: 'fx-3',
    name: 'Agua & Alcantarillado (SEMAPA)',
    categoryName: 'Servicios Básicos',
    type: 'FIXED_UTILITY',
    amount: 65.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 15,
    autoDeduct: true,
    color: '#06b6d4',
    icon: 'droplet',
    isPaidThisMonth: true,
  },
  {
    id: 'fx-4',
    name: 'Internet Fibra Óptica (Entel 100Mbps)',
    categoryName: 'Servicios Básicos',
    type: 'FIXED_UTILITY',
    amount: 195.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 20,
    autoDeduct: true,
    color: '#3b82f6',
    icon: 'wifi',
    isPaidThisMonth: true,
  },

  // Suscripciones Digitales & Ocio
  {
    id: 'fx-5',
    name: 'Netflix Premium 4K',
    categoryName: 'Suscripciones',
    type: 'SUBSCRIPTION',
    amount: 69.9,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 22,
    autoDeduct: true,
    color: '#dc2626',
    icon: 'tv',
    isPaidThisMonth: true,
  },
  {
    id: 'fx-6',
    name: 'Spotify Familiar',
    categoryName: 'Suscripciones',
    type: 'SUBSCRIPTION',
    amount: 45.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 28,
    autoDeduct: true,
    color: '#16a34a',
    icon: 'music',
    isPaidThisMonth: false,
  },
  {
    id: 'fx-7',
    name: 'ChatGPT Plus (OpenAI)',
    categoryName: 'Suscripciones',
    type: 'SUBSCRIPTION',
    amount: 20.0,
    currency: 'USD',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 30,
    autoDeduct: true,
    color: '#10b981',
    icon: 'sparkles',
    isPaidThisMonth: false,
  },
  {
    id: 'fx-8',
    name: 'Gimnasio Premier Cochabamba',
    categoryName: 'Salud & Deporte',
    type: 'SUBSCRIPTION',
    amount: 250.0,
    currency: 'BOB',
    billingFrequency: 'MONTHLY',
    dueDayOfMonth: 2,
    autoDeduct: false,
    color: '#f97316',
    icon: 'dumbbell',
    isPaidThisMonth: false,
  },
];

export const INITIAL_DEBTS_LOANS: MockDebtItem[] = [
  {
    id: 'debt-1',
    title: 'Préstamo viaje a La Paz',
    counterpartName: 'Carlos Mendoza',
    type: 'THEY_OWE_ME',
    totalAmount: 850.0,
    paidAmount: 350.0,
    currency: 'BOB',
    dueDate: '2026-09-15',
    notes: 'Quedó en pagar la mitad con su sueldo del 30',
    isSettled: false,
  },
  {
    id: 'debt-2',
    title: 'Anticipo proyecto freelance Web',
    counterpartName: 'Rodrigo Flores',
    type: 'THEY_OWE_ME',
    totalAmount: 1400.0,
    paidAmount: 1400.0,
    currency: 'BOB',
    dueDate: '2026-08-20',
    notes: 'Pago liquidado por transferencia BNB',
    isSettled: true,
  },
  {
    id: 'debt-3',
    title: 'Compra compartida pasajes',
    counterpartName: 'Mariana Silva',
    type: 'THEY_OWE_ME',
    totalAmount: 320.0,
    paidAmount: 0.0,
    currency: 'BOB',
    dueDate: '2026-09-05',
    notes: 'Boletos flota Cochabamba - Santa Cruz',
    isSettled: false,
  },
  {
    id: 'debt-4',
    title: 'Saldo Tarjeta de Crédito BCP Oro',
    counterpartName: 'Banco BCP',
    type: 'I_OWE',
    totalAmount: 1650.0,
    paidAmount: 700.0,
    currency: 'BOB',
    dueDate: '2026-09-10',
    notes: 'Pago mínimo cubierto, liquidar antes del 10 para 0 intereses',
    isSettled: false,
  },
  {
    id: 'debt-5',
    title: 'Préstamo familiar (Arreglo auto)',
    counterpartName: 'Tío Roberto',
    type: 'I_OWE',
    totalAmount: 2000.0,
    paidAmount: 1000.0,
    currency: 'BOB',
    dueDate: '2026-10-01',
    notes: 'Cuota de Bs. 500 por mes acordada',
    isSettled: false,
  },
];

export const INITIAL_COUPLES_EXPENSES: MockCoupleExpense[] = [
  {
    id: 'cpl-1',
    title: 'Súper Quincenal en Hipermaxi',
    totalAmount: 580.0,
    currency: 'BOB',
    category: 'Alimentación',
    paidBy: 'USER',
    userShareRatio: 0.5,
    partnerShareRatio: 0.5,
    date: '2026-08-26',
    isSettled: false,
  },
  {
    id: 'cpl-2',
    title: 'Cena Aniversario Typica & Vino',
    totalAmount: 240.0,
    currency: 'BOB',
    category: 'Restaurantes',
    paidBy: 'PARTNER',
    userShareRatio: 0.5,
    partnerShareRatio: 0.5,
    date: '2026-08-24',
    isSettled: false,
  },
  {
    id: 'cpl-3',
    title: 'Vacunas y control veterinario Toby',
    totalAmount: 180.0,
    currency: 'BOB',
    category: 'Mascotas',
    paidBy: 'USER',
    userShareRatio: 0.5,
    partnerShareRatio: 0.5,
    date: '2026-08-18',
    isSettled: false,
  },
  {
    id: 'cpl-4',
    title: 'Alquiler Departamento Cala Cala',
    totalAmount: 1800.0,
    currency: 'BOB',
    category: 'Hogar',
    paidBy: 'USER',
    userShareRatio: 0.5,
    partnerShareRatio: 0.5,
    date: '2026-08-05',
    isSettled: true,
  },
];

export const INITIAL_SAVINGS_GOALS = [
  {
    id: 'sg-1',
    title: 'Fondo de Emergencia (6 Meses)',
    targetAmount: 30000.0,
    currentAmount: 18500.0,
    currency: 'BOB',
    deadlineDate: '2026-12-31',
    color: '#10b981',
    icon: 'shield-check',
    monthlyRequiredContribution: 2875.0,
  },
  {
    id: 'sg-2',
    title: 'Vacaciones Fin de Año (Playa)',
    targetAmount: 1500.0,
    currentAmount: 950.0,
    currency: 'USD',
    deadlineDate: '2026-12-15',
    color: '#06b6d4',
    icon: 'palmtree',
    monthlyRequiredContribution: 137.5,
  },
  {
    id: 'sg-3',
    title: 'Cuota Inicial Auto Nuevo',
    targetAmount: 5000.0,
    currentAmount: 2100.0,
    currency: 'USD',
    deadlineDate: '2027-06-30',
    color: '#8b5cf6',
    icon: 'car',
    monthlyRequiredContribution: 290.0,
  },
];
